spring.application.name=13_DemoApp

spring.datasource.url=jdbc:mysql://localhost:3306/DEMO_APP
spring.datasource.username=root
spring.datasource.password=tiger
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update